backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
    - name: "cards"
      label: "Card"
      folder: "cards"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Date", name: "date", widget: "datetime"}
        - {label: "Tags", name: "tags", widget: "list", required: false}
        - {label: "Body", name: "body", widget: "markdown", required: false}